apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chat-backend
  labels:
    app: chat-app
    component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chat-app
      component: backend
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
