apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret
  namespace: lab5-chat-prod
type: Opaque
stringData:
  database-url: "postgresql://chat:REPLACE_ME_VIA_CI@postgres-0.postgres.lab5-chat-dev.svc.cluster.local:5432/chat?sslmode=disable"
