apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab5-chat-dev

resources:
  - ../../base
  - secret.yaml

patches:
  - path: patch-configmap.yaml
  - path: patch-backend.yaml

commonLabels:
  environment: dev
