apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret
  namespace: lab5-chat-dev
type: Opaque
stringData:
  database-url: "postgresql://chat:chat@postgres-0.postgres:5432/chat?sslmode=disable"
