apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-infra.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  postgres-password: {{ .Values.password | quote }}
  database: {{ .Values.auth.database | quote }}
