apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chat-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.backend.port }}"
  CORS_ORIGIN: {{ .Values.config.corsOrigin | quote }}
  MAX_MESSAGES: {{ .Values.config.maxMessages | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}

