apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat-app.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
